version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.9

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.9
      - run:
          name: Build Docker Image
          command: |
            docker build -t vaibhavgawad/sih:1 .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push vaibhavgawad/sih:1
