version: 2.1
jobs:
  build:
    docker:
      - image: docker

    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            cd real-estate-react-assignment
            docker build -t vaibhavgawad/sih:1 .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push vaibhavgawad/sih:1
